// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contact: dynamic(() => import("./Contact")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  hero_text: dynamic(() => import("./HeroText")),
  services: dynamic(() => import("./Services")),
  testimonials: dynamic(() => import("./Testimonials")),
  workspace: dynamic(() => import("./Workspace")),
};
